"""Generate the Clima Saúde Community logo assets from one geometry definition.

Writes:
  branding/logo.svg                                         master artwork (108 x 108)
  androidApp/src/main/res/drawable/ic_launcher_background.xml
  androidApp/src/main/res/drawable/ic_launcher_foreground.xml
  androidApp/src/main/res/drawable/ic_launcher_monochrome.xml  themed (Android 13+) icon
  androidApp/src/main/res/drawable/ic_notification.xml         status-bar icon
  iosApp/Assets.xcassets/AppIcon.appiconset/AppIcon.png     1024 x 1024, opaque

The in-app mark (shared/.../presentation/components/BrandMark.kt) uses the same path
strings; update it too when the geometry below changes.

Usage: py scripts/generate-app-icon.py   (needs Pillow: py -m pip install pillow)
"""
import math
import os

from PIL import Image, ImageChops, ImageDraw

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Colours
TEAL_DARK = "#0D5B58"
TEAL_LIGHT = "#138E7B"
SUN = "#F4B942"
WHITE = "#FFFFFF"

# Geometry on the 108 x 108 adaptive-icon canvas; keep it inside the 66dp safe circle.
DROP_CENTER, DROP_RADIUS, DROP_TIP_Y = (54.0, 54.0), 15.0, 24.0
CROSS = [(51, 48), (57, 48), (57, 53), (62, 53), (62, 59), (57, 59), (57, 64), (51, 64),
         (51, 59), (46, 59), (46, 53), (51, 53)]
SUN_CENTER, SUN_RADIUS = (68.0, 36.0), 9.0
ARC_CENTER, ARC_RADIUS, ARC_WIDTH = (54.0, 54.0), 22.0, 5.0
ARCS = [(25.0, 80.0), (100.0, 155.0)]  # degrees, clockwise from 3 o'clock


def fmt(value):
    return f"{value:.2f}".rstrip("0").rstrip(".")


def polar(center, radius, degrees):
    a = math.radians(degrees)
    return center[0] + radius * math.cos(a), center[1] + radius * math.sin(a)


def drop_tangents():
    cx, cy = DROP_CENTER
    # The tip-to-circle tangents touch at +-60 degrees from "up" when the tip is 2r away.
    half = math.degrees(math.acos(DROP_RADIUS / (cy - DROP_TIP_Y)))
    return polar(DROP_CENTER, DROP_RADIUS, -90 + half), polar(DROP_CENTER, DROP_RADIUS, -90 - half)


def drop_path():
    right, left = drop_tangents()
    r = fmt(DROP_RADIUS)
    cross = "M" + " L".join(f"{fmt(x)},{fmt(y)}" for x, y in CROSS) + " Z"
    return (f"M{fmt(DROP_CENTER[0])},{fmt(DROP_TIP_Y)} L{fmt(right[0])},{fmt(right[1])} "
            f"A{r},{r} 0 1,1 {fmt(left[0])},{fmt(left[1])} Z {cross}")


def sun_path():
    x, y = SUN_CENTER
    r = SUN_RADIUS
    return (f"M{fmt(x - r)},{fmt(y)} A{fmt(r)},{fmt(r)} 0 1,1 {fmt(x + r)},{fmt(y)} "
            f"A{fmt(r)},{fmt(r)} 0 1,1 {fmt(x - r)},{fmt(y)} Z")


def arc_path(start, end):
    sx, sy = polar(ARC_CENTER, ARC_RADIUS, start)
    ex, ey = polar(ARC_CENTER, ARC_RADIUS, end)
    r = fmt(ARC_RADIUS)
    return f"M{fmt(sx)},{fmt(sy)} A{r},{r} 0 0,1 {fmt(ex)},{fmt(ey)}"


def write(path, text):
    full = os.path.join(ROOT, path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("wrote", path)


def svg():
    arcs = "\n".join(
        f'  <path d="{arc_path(s, e)}" fill="none" stroke="{WHITE}" '
        f'stroke-width="{fmt(ARC_WIDTH)}" stroke-linecap="round"/>' for s, e in ARCS)
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 108 108" width="1080" height="1080">
  <!-- Clima Saude Community. Generated by scripts/generate-app-icon.py; do not edit by hand. -->
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="{TEAL_DARK}"/>
      <stop offset="1" stop-color="{TEAL_LIGHT}"/>
    </linearGradient>
  </defs>
  <rect width="108" height="108" fill="url(#bg)"/>
  <path d="{sun_path()}" fill="{SUN}"/>
  <path d="{drop_path()}" fill="{WHITE}" fill-rule="evenodd"/>
{arcs}
</svg>
"""


def android_background():
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate-app-icon.py; do not edit by hand. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path android:pathData="M0,0 H108 V108 H0 Z">
        <aapt:attr name="android:fillColor">
            <gradient
                android:type="linear"
                android:startX="0"
                android:startY="0"
                android:endX="108"
                android:endY="108"
                android:startColor="{TEAL_DARK}"
                android:endColor="{TEAL_LIGHT}" />
        </aapt:attr>
    </path>
</vector>
"""


def android_foreground():
    arcs = "".join(f"""
    <path
        android:pathData="{arc_path(s, e)}"
        android:strokeColor="{WHITE}"
        android:strokeWidth="{fmt(ARC_WIDTH)}"
        android:strokeLineCap="round" />""" for s, e in ARCS)
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate-app-icon.py; do not edit by hand. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path
        android:fillColor="{SUN}"
        android:pathData="{sun_path()}" />
    <path
        android:fillColor="{WHITE}"
        android:fillType="evenOdd"
        android:pathData="{drop_path()}" />{arcs}
</vector>
"""


def android_monochrome(size_dp, viewport, offset_x=0, offset_y=0):
    """Single-colour mark (sun omitted) for themed launcher icons and the notification icon."""
    arcs = "".join(f"""
        <path
            android:pathData="{arc_path(s, e)}"
            android:strokeColor="{WHITE}"
            android:strokeWidth="{fmt(ARC_WIDTH)}"
            android:strokeLineCap="round" />""" for s, e in ARCS)
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate-app-icon.py; do not edit by hand. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{size_dp}dp"
    android:height="{size_dp}dp"
    android:viewportWidth="{viewport}"
    android:viewportHeight="{viewport}">
    <group
        android:translateX="{fmt(-offset_x)}"
        android:translateY="{fmt(-offset_y)}">
        <path
            android:fillColor="{WHITE}"
            android:fillType="evenOdd"
            android:pathData="{drop_path()}" />{arcs}
    </group>
</vector>
"""


def ios_png(size=1024, supersample=4):
    """iOS shows the whole square (it applies its own mask), so crop to the visible 72dp."""
    big = size * supersample
    scale = big / 72.0

    def p(x, y):
        return (x - 18) * scale, (y - 18) * scale

    # Diagonal gradient background.
    vertical = Image.linear_gradient("L").resize((big, big))
    mask = ImageChops.add(vertical, vertical.transpose(Image.TRANSPOSE), scale=2)
    background = Image.composite(Image.new("RGB", (big, big), TEAL_LIGHT),
                                 Image.new("RGB", (big, big), TEAL_DARK), mask)
    image = background.copy()
    draw = ImageDraw.Draw(image)

    sx, sy = p(*SUN_CENTER)
    sr = SUN_RADIUS * scale
    draw.ellipse((sx - sr, sy - sr, sx + sr, sy + sr), fill=SUN)

    right, left = drop_tangents()
    start = math.degrees(math.atan2(right[1] - DROP_CENTER[1], right[0] - DROP_CENTER[0]))
    end = math.degrees(math.atan2(left[1] - DROP_CENTER[1], left[0] - DROP_CENTER[0])) + 360
    outline = [p(DROP_CENTER[0], DROP_TIP_Y)] + [
        p(*polar(DROP_CENTER, DROP_RADIUS, start + (end - start) * i / 180)) for i in range(181)]
    draw.polygon(outline, fill=WHITE)
    # Cut the cross out by repainting it with the background underneath.
    cross_mask = Image.new("L", (big, big), 0)
    ImageDraw.Draw(cross_mask).polygon([p(x, y) for x, y in CROSS], fill=255)
    image.paste(background, (0, 0), cross_mask)
    draw = ImageDraw.Draw(image)

    # Each arc is a filled band with round caps, which renders cleaner than a wide line.
    half = ARC_WIDTH * scale / 2
    for s, e in ARCS:
        steps = [s + (e - s) * i / 90 for i in range(91)]
        outer = [p(*polar(ARC_CENTER, ARC_RADIUS + ARC_WIDTH / 2, a)) for a in steps]
        inner = [p(*polar(ARC_CENTER, ARC_RADIUS - ARC_WIDTH / 2, a)) for a in reversed(steps)]
        draw.polygon(outer + inner, fill=WHITE)
        for a in (s, e):
            x, y = p(*polar(ARC_CENTER, ARC_RADIUS, a))
            draw.ellipse((x - half, y - half, x + half, y + half), fill=WHITE)

    path = os.path.join(ROOT, "iosApp/Assets.xcassets/AppIcon.appiconset/AppIcon.png")
    image.resize((size, size), Image.LANCZOS).save(path, optimize=True)
    print("wrote", os.path.relpath(path, ROOT))


if __name__ == "__main__":
    write("branding/logo.svg", svg())
    write("androidApp/src/main/res/drawable/ic_launcher_background.xml", android_background())
    write("androidApp/src/main/res/drawable/ic_launcher_foreground.xml", android_foreground())
    write("androidApp/src/main/res/drawable/ic_launcher_monochrome.xml",
          android_monochrome(108, 108))
    # The mark spans x 31.5..76.5 and y 24..78.5 on the 108 canvas; centre it in a 58 viewport.
    write("androidApp/src/main/res/drawable/ic_notification.xml",
          android_monochrome(24, 58, 25, 22.25))
    ios_png()
    print("drop:", drop_path())
    print("sun:", sun_path())
    for s, e in ARCS:
        print("arc:", arc_path(s, e))
